apiVersion: v1
kind: Secret
metadata:
  name: {{ template "vault-certificates-exporter.fullname" . }}-token
  labels:
    chart: {{ template "vault-certificates-exporter.chart" . }}
    app: {{ template "vault-certificates-exporter.name" . }}
    release: "{{ .Release.Name }}"
    heritage: "{{ .Release.Service }}"
type: Opaque
data:
  token: "{{ .Values.vault.token | b64enc }}"